services:
  db:
    image: postgres:17.6
    container_name: openmarket-postgres
    restart: unless-stopped
    ports:
      - '5432:5432' # change left side if 5432 is already used (e.g. "15432:5432")
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U dev -d openmarket']
      interval: 2s
      timeout: 2s
      retries: 15

  # optional web DB UI (http://localhost:8080)
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_data:
